### ISSUE TITLE
Status command not working after update v3.1

### ISSUE THREAD

**Issue by markisoke** [sethforprivacy/p2pool-docker#36]
Used to work like a charm, but now when I run:

`docker attach p2pool
status`

It doesn't show anything anymore.

Also, it won't exit by Ctrl+P Crtl+Q.
I have to exit by Ctrl+C and p2pool will keep running.

**Comment by sethforprivacy** [comment]
Digging into this now, thanks for the report!

**Comment by sethforprivacy** [comment]
@markisoke this still works perfectly for me on multiple hosts with v3.1.

Are you sure you're doing the command properly?

It should be:

`docker attach p2pool`

And then in the resulting command line you can enter:

`status`

And get the full output of the command or enter other commands as you wish.

**Comment by markisoke** [comment]
Yes, the commands are filled out as you mentioned above:

![image](https://user-images.githubusercontent.com/12715660/228556368-746137f4-d1ac-4969-af05-a411a63c1e34.png)

Also Ctrl+P and Ctrl+Q doesn't work:

![image](https://user-images.githubusercontent.com/12715660/228556660-68cedf77-58f5-43e2-b052-75d3edac0a01.png)

This happened after the update.

**Comment by markisoke** [comment]
Yes, p2pool was running correctly, it even found a block with this problem.
I tried rebooting the machine and recreating the container but it didn't help.

This morning I deleted the container and created it again and that seems to have done the trick, my status command is now working again.

**Comment by sethforprivacy** [comment]
Very interesting, thanks for reporting! As it's fixed I'll close this for now, but please let me know if you experience it again in the future.
