### ISSUE TITLE
Tor Proxy

### ISSUE THREAD

**Issue by JohnGalt1717** [sethforprivacy/p2pool-docker#4]
How does one specify to use Tor to proxy outgoing?  In your sample on your blog, it definately exposes incoming through Tor and only tor, but it doesn't proxy outgoing as far as I can tell. (this is true of the monerod too, but it looks like adding --tx-proxy tor ... works there)

PS, it would be nice if your entire configuration with Tor forced everything through Tor, and killed all other networking other than to the host network.

**Comment by sethforprivacy** [comment]
Again, this isn't very applicable to p2pool, but you don't necessarily want p2p data going over Tor for several reasons:

- Drastically increasing load on the Tor network
- Drastically increasing sync times and block propagation lag
- Drastically increased risk of Sybil attacks
- Drastically simplified eclipse attacks

p2pool *especially* should not normally be run Tor-only, as you will have severely delayed block propagation leading to a very high uncle rate and many missed blocks on the mainchain.

**Comment by JohnGalt1717** [comment]
So what's the solution to mine anonymously then? Because if the incoming and outgoing traffic from p2pool is not obfuscated with Tor, then it's a trivial exercise to unmask the wallet.
