### ISSUE TITLE
release tags ?

### ISSUE THREAD

**Issue by marvin8** [sethforprivacy/p2pool-docker#5]
Now that P2Pool itself has a couple of tagged releases, I think it'd be handy to have tagged versions of the docker images.

I am unsure on how this would be done / configures, otherwise I'd have created a pull request... sorry.

**Comment by sethforprivacy** [comment]
Will push tagged version and switch to those with weekly rebuilds today.

Thanks for the call out!

**Comment by sethforprivacy** [comment]
New tagged release is live now, and "latest" is migrated to the latest tagged release:

https://hub.docker.com/r/sethsimmons/p2pool/tags?page=1&ordering=last_updated

**Comment by marvin8** [comment]
Thanks Seth... very much appreciated.
